### ISSUE TITLE
Fix FuzzySets to return list of MembershipDegrees when passed collection.

### ISSUE THREAD

**Issue by Adrian-Chlopowiec** [PWR-Informatyka-biomedyczna/DoggOSFuzzy#30]
If user passes a collection to FuzzySet.__call__ we expect it to return a collection of MembershipDegree.

**Comment by konrad-karanowski** [comment]
What if the user gives np.ndarray? Do we return np.ndarray MembershipDegree or do we return the list?

**Comment by konrad-karanowski** [comment]
In my opinion, Membership degree does not make sense. We add a class that only causes overhead, our fuzzy sets return some strange things instead of floats, it's hard to vectorize.
