### ISSUE TITLE
Implement Antecedent

### ISSUE THREAD

**Issue by Adrian-Chlopowiec** [PWR-Informatyka-biomedyczna/DoggOSFuzzy#6]
-Validate type integrity across Clauses.
-Develop optimal firing_value evaluation method.

**Comment by Aleksy-niamik** [comment]
interface Antecedent
    @property
   - fire: Callable[(dict[Clause, MembershipDegree]), MembershipDegree]
   @property
   - algebra: Algebra

Term : Antecedent
   - Term (Clause clause, Algebra algebra):
       self.algebra = algebra
       self.fire = lambda dic -> dic[clause]
   - __and__ (Term term):
       return __class__ { algebra = algebra, fire = self.algebra.t_norm(self.fire(dic), term.fire(dic))}
   - __or__ (Term term):
       return __class__ { algebra = algebra, fire = self.algebra.s_norm(self.fire(dic), term.fire(dic))}
